MODEL:
  TYPE: refine_reslite
  SIZE: '512'
  REFINE: True
  CONV_BODY: refine_reslite.RefineResnet18lite
  NUM_CLASSES: 2
  LOAD_PRETRAINED_WEIGHTS: True
  PRETRAIN_WEIGHTS: './weights/pretrained_models/resnet18-5c106cde.pth'

TRAIN:
  OVERLAP: 0.5
  BGR_MEAN: [104, 117, 123]
  BATCH_SIZE: 64
  OHEM: True
  NEG_RATIO: 5
  WARMUP: True
  WARMUP_EPOCH: 5
  TRAIN_ON: True

BIG:
  FEATURE_MAPS: [[32, 32], [16, 16], [8, 8], [4, 4]]
  ARM_CHANNELS: [128, 256, 512, 256]
  ODM_CHANNELS: [128, 128, 128, 128]
  NUM_ANCHORS: [3, 3, 3, 2]
  STEPS: [[16, 16], [32, 32], [64, 64], [128, 128]]
  MIN_SIZES: [30, 64, 128, 280]
  MAX_SIZES: [64, 128, 280, 352]
  ASPECT_RATIOS : [[0.25, 0.5], [0.25, 0.5], [0.25, 0.5], [0.5]]
  CLIP: True
  IMG_WH: [512, 512]
  INPUT_FIXED: True # if you want to input different size, you need to set this False.
  USE_MAX_SIZE: False

SOLVER:
  WEIGHT_DECAY: 0.0005
  BASE_LR: 0.01
  GAMMA: 0.1
  MOMENTUM: 0.9
  EPOCH_STEPS: [0, 200, 250]  
  END_EPOCH: 300
  START_EPOCH: 0

DATASETS:
  TRAIN_TYPE: [['2007', 'trainval'], ['2012', 'trainval']]
  VAL_TYPE: [['2007', 'test']]
  DATAROOT: 'data/datasets/VOCdevkit/'
  DATA_TYPE: 'VOC'
  SETS:
    VOC: [['0712', '0712_trainval']]
    VOC0712PLUS: [['0712', '0712_trainval_test']]
    VOC0712: [['2012', '2012_trainval']]
    COCO: [['2014', 'train'], ['2014', 'valminusminival']]
    VOC2007: [['0712', "2007_test"]]
    COCOval: [['2014', 'minival']]
    VOCROOT: 'data/datasets/VOCdevkit0712/'
    COCOROOT: 'data/datasets/coco2015'
  
TEST:
  INPUT_WH: [512, 512]
  CONFIDENCE_THRESH: 0.3
  NMS_OVERLAP: 0.3
  BATCH_SIZE: 16
